#!/usr/bin/env groovy
@Library('cicd-common@master')
import com.att.eg.cicd.*

env.environment = 'dev-int'
env.platform = 'java.couchbase'
env.appDeploy = 'true'
env.apiGatewayDeploy = 'true'

def workflow = new WorkflowFactory().getWorkflow(env.platform, this)
workflow.create()